### ISSUE TITLE
Restart function does not work

### ISSUE THREAD

**Issue by sanja9** [joysfera/nodemcu-web-ide#1]
First of all I would like to say that you have done a realy great work. Thanks for that! However, while playing around with the functions I found out that if you trigger the "Restart" function the "Please wait" message shows up but the esp itself does not restart. Any idea how to fix it? Thanks and greetings

**Comment by midiway** [comment]
change line 193 to:
```
message[#message + 1] = "</table><a href='#' onclick='v=prompt(\"Filename\");if (v!=null) { this.href=\"/\"+v+\"?edit\"; return true;} else return false;'>Create new</a> &nbsp; &nbsp; <a href='#' onclick='var x=new XMLHttpRequest();x.open(\"GET\",\"/?restart\");x.send();setTimeout(function(){location.href=\"/\"},5000);this.innerText=\"Plz wait..\";return false'>Restart</a>"
```

**Comment by joysfera** [comment]
Restart fixed in https://github.com/joysfera/nodemcu-web-ide/commit/d45bd1d3b52bbf6510ef53fad51fbaa75d6ce3cc
