### ISSUE TITLE
Implementing your code in other code

### ISSUE THREAD

**Issue by Timmiej93** [joysfera/nodemcu-web-ide#3]
Hi,

I'd like to implement your code in a project I'm working on. Since this project also requires a TCP server, I have had to incorporate your code into the other script I already had. Can I share this edited code online? It will always be completely open source, free of charge, etc. I'm basically just using the code in the `conn:on("receive", ` and `conn:on("sent", ` sections, and applying them elsewhere.

Tim

**Comment by joysfera** [comment]
The ``conn:on("receive")`` and ``conn:on("sent")`` are not my inventions, I think I learnt them when following the NodeMCU development. Feel free to use them anywhere you wish.
